version: '3.8'
services:
  company-service:
    build: ./company-service
    ports:
      - "5001:5001"
    env_file:
      - .env

  categories-service:
    build: ./categories-service
    ports:
      - "5002:5002"
    env_file:
      - .env